### ISSUE TITLE
Forked lab but the web page did not respond.

### ISSUE THREAD

**Issue by Cfrank482** [learn-co-curriculum/sinatra-nested-forms-readme#23] opened 2018-10-30 02:54 UTC

**Comment by drakeltheryuujin** [comment] 2018-11-07 17:31
Hi there,

It appears this issue is either a duplicate of, or included in, an existing issue found here: #22 

If you believe this issue is not already expressed in an un-closed issue on the repo, please re-open and provide further detail.

As always, thanks for contributing! 💙

**Closed by drakeltheryuujin** 2018-11-07 17:31 UTC
